[pytest]
testpaths = test_cases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -vs --html=reports/report.html --self-contained-html

markers =
    smoke: 冒烟测试
    regression: 回归测试
    e2e: 端到端测试
